apiVersion: v1
kind: ConfigMap
metadata:
  name: httpserver
data:
  config.yaml: |
    Server:
      RunMode: debug
      HttpPort: 80
      ReadTimeout: 60
      WriteTimeout: 60
    App:
      DefaultPageSize: 10
      MaxPageSize: 100
      LogSavePath: storage/logs
      LogFileName: app
      LogFileExt: .log
