{{- if .Values.ingress.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.secretName }}
data:
  tls.crt: {{ .Values.secret.tls.crt | quote }}
  tls.key: {{ .Values.secret.tls.key | quote }}
type: kubernetes.io/tls
{{- end }}
